#!/bin/zsh

# Get song metadata
metadata=$(dbus-send --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 --print-reply org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata')

# Get the album art's URL from the metadata 
echo $metadata | sed '/string "mpris:artUrl"/,+1!d' | sed '1d' | sed 's/^.*"\(.*\)".*$/\1/'
