#!/bin/bash

. "$HOME/.cache/wal/colors.sh"

if [ $# -eq 0 ]; then
	start=0
	stop=7
elif [ $# -eq 1 ]; then
	start=0
	stop=$1
elif [ $# -eq 2 ]; then
	start=$1
	stop=$2
fi

touch dyn
echo 'gradient = 1' >> dyn
printf "gradient_count = %s\n" "$(( $stop - $start))" >> dyn
for c in $(seq $start $stop); do
	color="color$c"
	printf "gradient_color_%s = '%s'\n" "$(($c - $start))" ${!color} >> dyn
done		
sed '/^gradient/d ; /\[color\]/rdyn' -i $HOME/.config/cava/tconfig
rm dyn
